// Create an instance of the FileSystemObject
var fso = new ActiveXObject("Scripting.FileSystemObject");

// Specify the path where the new VBS file will be created
var vbsFilePath = "C:\Users\Xx_Lo\OneDrive\Desktop\generatedCode.vbs";

// Use the CreateTextFile method to create the file
var vbsFile = fso.CreateTextFile(vbsFilePath, true);

// Write VBScript code to the file
vbsFile.WriteLine("' This is a generated VBScript file");
vbsFile.WriteLine("MsgBox \"Hello, I love my code!\"");
vbsFile.WriteLine("MsgBox \"This VBScript was generated by JavaScript!\"");

// Close the file
vbsFile.Close();

// Notify the user that the file has been created
WScript.Echo("VBScript file created at: " + vbsFilePath);
